import type { SophiaActionSignature } from "../lang/expression.js";
import type { SophiaRawAst } from "../lang/parser.js";
import {
  parseActionAst,
  parseCapabilityAst,
  parseEntityAst,
  parseErrorAst,
  parseStateAst,
  parseStorageAst,
  type ParsedAction,
  type ParsedCapability,
  type ParsedEntity,
  type ParsedState,
  type ParsedStorage,
} from "../lang/check_model.js";
import {
  sophiaTypeToTypeScript,
  type SophiaEntityTypes,
  type SophiaField,
  type SophiaStateTypes,
} from "../lang/types.js";
import { stableJson } from "../util/json.js";
import { indent } from "../util/strings.js";
import { emitBody } from "./ts_emit_body.js";

export interface SophiaSourceFile {
  path: string;
  ast: SophiaRawAst;
}

export function emitTypeScript(files: SophiaSourceFile[]): string {
  const domains = files.filter((file) => file.ast.kind === "domain");
  const entities = files.filter((file) => file.ast.kind === "entity");
  const capabilities = files.filter((file) => file.ast.kind === "capability");
  const states = files.filter((file) => file.ast.kind === "state");
  const storages = files.filter((file) => file.ast.kind === "storage");
  const errors = files.filter((file) => file.ast.kind === "error");
  const actions = files.filter((file) => file.ast.kind === "action");
  const parsedEntities = entities.map((file) => ({ file, entity: parseEntityAst(file.ast) }));
  const parsedCapabilities = capabilities.map((file) => ({
    file,
    capability: parseCapabilityAst(file.ast),
  }));
  const parsedStates = states.map((file) => ({ file, state: parseStateAst(file.ast) }));
  const parsedStorages = storages.map((file) => ({
    file,
    storage: parseStorageAst(file.ast),
  }));
  const parsedErrors = errors.map((file) => ({ file, error: parseErrorAst(file.ast) }));
  const parsedActions = actions.map((file) => ({ file, action: parseActionAst(file.ast) }));
  const entityTypes = buildEntityTypes(parsedEntities);
  const stateTypes = buildStateTypes(parsedStates);
  const actionTypes = buildActionTypes(parsedActions);
  const chunks = [
    "/* Generated by Sophia v0 deterministic TypeScript backend. */",
    "export type Unit = void;",
    "export interface SophiaEffects { write(value: string): void; }",
    "export const defaultEffects: SophiaEffects = { write: (value: string) => console.log(value) };",
    "",
    `export const domains = ${stableJson(domains.map((file) => nodeMetadata(file)))} as const;`,
    "",
    `export const entities = ${stableJson(parsedEntities.map(({ file, entity }) => entityMetadata(file, entity)))} as const;`,
    "",
    ...parsedEntities.map(({ entity }) => emitEntityInterface(entity)),
    "",
    `export const states = ${stableJson(parsedStates.map(({ file, state }) => stateMetadata(file, state)))} as const;`,
    "",
    ...parsedStates.map(({ state }) => emitStateType(state)),
    "",
    `export const capabilities = ${stableJson(parsedCapabilities.map(({ file, capability }) => capabilityMetadata(file, capability)))} as const;`,
    "",
    `export const storages = ${stableJson(parsedStorages.map(({ file, storage }) => storageMetadata(file, storage)))} as const;`,
    "",
    `export const errors = ${stableJson(parsedErrors.map(({ file, error }) => errorMetadata(file, error)))} as const;`,
    "",
    `export const actions = ${stableJson(parsedActions.map(({ file, action }) => actionMetadata(file, action)))} as const;`,
    "",
    ...parsedActions.map(({ action }) => emitAction(action, entityTypes, stateTypes, actionTypes)),
  ];
  return `${chunks.join("\n")}\n`;
}

function emitAction(
  action: ParsedAction,
  entityTypes: SophiaEntityTypes,
  stateTypes: SophiaStateTypes,
  actionTypes: Map<string, SophiaActionSignature>,
): string {
  const inputFields = action.inputFields;
  const outputType = action.outputType ?? "Unit";
  const paramsType = inputFields.length > 0 ? emitObjectType(inputFields) : "Record<string, never>";
  const returnType = sophiaTypeToTypeScript(outputType);
  const statements = emitBody({
    body: action.body,
    types: new Map(inputFields.map((field) => [field.name, field.type])),
    outputType,
    entityTypes,
    stateTypes,
    actionTypes,
  });
  const destructure =
    inputFields.length > 0
      ? `\n  const { ${inputFields.map((field) => field.name).join(", ")} } = input;`
      : "";
  return `export function ${action.name}(input: ${paramsType} = {} as ${paramsType}, effects: SophiaEffects = defaultEffects): ${returnType} {${destructure}
${indent(statements, 2)}
}`;
}

function emitObjectType(fields: SophiaField[]): string {
  return `{ ${fields.map((field) => `${field.name}: ${sophiaTypeToTypeScript(field.type)}`).join("; ")} }`;
}

function buildEntityTypes(entities: Array<{ entity: ParsedEntity }>): SophiaEntityTypes {
  return new Map(entities.map(({ entity }) => [entity.name, entity.fields]));
}

function buildStateTypes(states: Array<{ state: ParsedState }>): SophiaStateTypes {
  return new Map(states.map(({ state }) => [state.name, state.values]));
}

function buildActionTypes(
  actions: Array<{ action: ParsedAction }>,
): Map<string, SophiaActionSignature> {
  return new Map(
    actions.map(({ action }) => [
      action.name,
      {
        name: action.name,
        input: action.inputFields,
        outputType: action.outputType ?? "Unit",
        effects: action.effects,
        errors: action.errors,
      },
    ]),
  );
}

function emitEntityInterface(entity: ParsedEntity): string {
  return `export interface ${entity.name} {
${indent(
  entity.fields.map((field) => `${field.name}: ${sophiaTypeToTypeScript(field.type)};`).join("\n"),
  2,
)}
}`;
}

function emitStateType(state: ParsedState): string {
  return `export const ${state.name} = {
${indent(state.values.map((value) => `${value}: "${value}",`).join("\n"), 2)}
} as const;
export type ${state.name} = (typeof ${state.name})[keyof typeof ${state.name}];`;
}

function nodeMetadata(file: SophiaSourceFile) {
  return metadata(file);
}

function capabilityMetadata(file: SophiaSourceFile, capability: ParsedCapability) {
  return metadata(file, {
    allow: capability.allow,
    deny: capability.deny,
  });
}

function entityMetadata(file: SophiaSourceFile, entity: ParsedEntity) {
  return metadata(file, {
    fields: entity.fields,
  });
}

function stateMetadata(file: SophiaSourceFile, state: ParsedState) {
  return metadata(file, {
    values: state.values,
  });
}

function storageMetadata(file: SophiaSourceFile, storage: ParsedStorage) {
  return metadata(file, {
    key: storage.keyType,
    value: storage.valueType,
  });
}

function errorMetadata(file: SophiaSourceFile, error: ReturnType<typeof parseErrorAst>) {
  return metadata(file, {
    variants: error.variants.map((variant) => ({
      name: variant.name,
      fields: variant.fields,
    })),
  });
}

function actionMetadata(file: SophiaSourceFile, action: ParsedAction) {
  return metadata(file, {
    input: action.inputFields,
    output: action.outputFields,
    effects: [...action.effects],
    errors: [...action.errors],
  });
}

function metadata<T extends Record<string, unknown> = Record<string, never>>(
  file: SophiaSourceFile,
  payload = {} as T,
): { name: string; path: string } & T {
  return { name: file.ast.name, path: file.path, ...payload };
}
